language: ruby
rvm:
  - 1.9.3

env:
  - DB=sqlite

script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake assets:precompile

notifications: 
  email: false
  irc: 
    channels:
    - ircnet.eversible.com#tmskanava
    use_notice: true
    skip_join: true
    template:
    - "----"
    - "%{message}"
    - "%{repository}/%{branch}#%{build_number} (%{author})"
    - "Build details : %{build_url}"
    - "----"

# whitelist
branches:
  only:
    - master
    - develop

env:
  global:
    secure: "Boa7mIucDkkRVyRtagSDc0dZJ2hEdGg725yWmd9xJh+2WyenaqESdGEZFtUG\nMJuaWEiH7G889ya2yaJC65kI5NsNuIprXT84J5ylu1ExaBMKuHAV/zoHkmxT\nkzvvUYAufRK1keJojOPO1HJ7D9mtAecTCyrcu5M+1ss7LDi3jxk="

after_script:
  - gem install heroku
  - yes | ruby travis_deployer.rb
  - heroku keys:clear
  - yes | heroku keys:add
  - git push heroku master # or whatever your heroku push looks like
