language: ruby
rvm:
  - 1.9.3

notifications: 
  email: false
  irc: 
    channels:
    - ircnet.eversible.com#tmskanava
    use_notice: true
    skip_join: true
    template:
    - "----"
    - "%{message}"
    - "%{repository}/%{branch}#%{build_number} (%{author})"
    - "Build details : %{build_url}"
    - "----"

# whitelist
branches:
  only:
    - master
    - develop
